name: cnnproject
channels:
  - defaults
  - pytorch
  - conda-forge
dependencies:
  - python=3.10
  - numpy>=1.24
  - pillow>=10.0
  - pandas>=2.0
  - matplotlib>=3.7
  - scikit-learn>=1.3
  - tqdm>=4.65
  - pytorch>=2.0
  - torchvision>=0.15
  - pip
  - pip:
      - jupyter
